#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp.

# Check the number of arguments provided
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    # The script requires at least 3 arguments: PATH_TO_FILE, IP, and USERNAME.
    # An optional 4th argument, PATH_TO_SSH_KEY, can be provided.    exit 1 # Exit with an error status
fi

# If only 3 arguments are provided
if [ "$#" -lt 4 ]; then
    # Use scp with StrictHostKeyChecking disabled to transfer the file
    # $1: PATH_TO_FILE, $3: USERNAME, $2: IP
    scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
    # Use scp with the specified SSH key and StrictHostKeyChecking disabled to transfer the file
    # $1: PATH_TO_FILE, $4: PATH_TO_SSH_KEY, $3: USERNAME, $2: IP
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi

