#!/usr/bin/env bash
# Installs and configures the Nginx web server.

# Update package repositories
apt-get update

# Install Nginx
apt-get -y install nginx

# Allow incoming HTTP traffic
ufw allow 'Nginx HTTP'

# Create a simple HTML file
echo "Hello World!" > /var/www/html/index.html

# Start Nginx service
service nginx -t

# Display a message indicating successful installation
sudo service nginx restart
