#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

# Update package repositories
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\\n\\trewrite ^\\/redirect_me https:\/\/github.com/\yusuufm permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart
