#!/usr/bin/env bash
# Fixes server bug
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
# Stop any running Apache server
pkill apache2
# Restart Nginx as the nginx user
su nginx -s /bin/bash -c 'nginx -s reload'
